import { ChecklistTask, StageProgress } from './types.js';

export const STAGES_PROGRESS: StageProgress[] = [
  {
    stageNumber: 1,
    stageName: 'Giai đoạn 1',
    title: 'Khảo Sát & Định Vị Sản Phẩm (Discovery & Product Definition)',
    status: 'COMPLETED',
    completedPercent: 100,
    totalTasks: 4,
    completedTasks: 4,
    description: 'Xác lập PRD, OKRs, 5 Luồng tương tác cốt lõi, Ma trận RBAC/ABAC và Lõi Auth bảo mật cao.',
  },
  {
    stageNumber: 2,
    stageName: 'Giai đoạn 2',
    title: 'Thiết Kế UI/UX & Kiến Trúc Hệ Thống (Design & Architecture)',
    status: 'COMPLETED',
    completedPercent: 100,
    totalTasks: 6,
    completedTasks: 6,
    description: 'Lược đồ PostgreSQL 16 mở rộng ltree, Design Tokens, OpenAPI 3.1, Redis Lua Voting và Flatten Tree O(N).',
  },
  {
    stageNumber: 3,
    stageName: 'Giai đoạn 3',
    title: 'Thiết Lập Nền Tảng & Môi Trường DevOps (Foundation & DevOps Setup)',
    status: 'COMPLETED',
    completedPercent: 100,
    totalTasks: 5,
    completedTasks: 5,
    description: 'Docker Compose 4 containers, Multi-stage Docker builds (<100MB), CI/CD 4 Cổng GitHub Actions và Render Blueprint.',
  },
  {
    stageNumber: 4,
    stageName: 'Giai đoạn 4',
    title: 'Phát Triển Lõi & Tích Hợp Hệ Thống (Core Development & Integration)',
    status: 'IN_PROGRESS',
    completedPercent: 35,
    totalTasks: 7,
    completedTasks: 2,
    description: 'Hiện thực hóa toàn diện Phân hệ Auth 4.1 (Hoàn thành 100%), chuẩn bị phân hệ CMS & Thảo luận cộng đồng.',
  },
  {
    stageNumber: 5,
    stageName: 'Giai đoạn 5',
    title: 'Kiểm Thử & Đảm Bảo Chất Lượng (Testing & QA)',
    status: 'PLANNED',
    completedPercent: 0,
    totalTasks: 5,
    completedTasks: 0,
    description: 'Kiểm thử tải (K6/Artillery), E2E Testing (Playwright), Chaos Testing và bảo mật DAST/SAST.',
  },
  {
    stageNumber: 6,
    stageName: 'Giai đoạn 6',
    title: 'Gia Cố Sản Xuất & Tối Ưu Hóa (Production Hardening & Optimization)',
    status: 'PLANNED',
    completedPercent: 0,
    totalTasks: 4,
    completedTasks: 0,
    description: 'Bảo mật SSL mTLS, cấu hình WAF Cloudflare, giám sát Prometheus/Grafana, tối ưu truy vấn SQL EXPLAIN ANALYZE.',
  },
  {
    stageNumber: 7,
    stageName: 'Giai đoạn 7',
    title: 'Triển Khai & Vận Hành Hậu Phát Hành (Launch & Post-Launch Operations)',
    status: 'PLANNED',
    completedPercent: 0,
    totalTasks: 4,
    completedTasks: 0,
    description: 'Chiến lược Canary / Blue-Green Deployment, sao lưu tự động WAL-G, Runbook ứng cứu sự cố và kế hoạch mở rộng.',
  },
];

export const CHECKLIST_TASKS: ChecklistTask[] = [
  // GIAI ĐOẠN 1
  {
    id: 'task-1-1',
    stageNumber: 1,
    title: 'Xây dựng Hồ sơ Yêu cầu Sản phẩm (PRD)',
    description: 'Định nghĩa tầm nhìn, mục tiêu kinh doanh, OKRs, 3 Chân dung người dùng (Junior Dev, Lead Engineer, System Architect).',
    status: 'COMPLETED',
    deliverables: ['docs/stage-1/PRD_STAGE_1_DISCOVERY.md'],
    verificationCriteria: 'Đầy đủ 5 User Journeys, chỉ số đo lường hiệu năng p95 < 200ms.',
    tag: 'Product',
  },
  {
    id: 'task-1-2',
    stageNumber: 1,
    title: 'Đặc tả An ninh & Ma trận RBAC / ABAC',
    description: 'Thiết kế 5 vai trò (Guest, User, SpaceMod, GlobalMod, Admin) và các điều kiện ABAC (Karma, Account Age, Ownership).',
    status: 'COMPLETED',
    deliverables: ['docs/stage-1/AUTH_SECURITY_SPECIFICATION.md', 'services/auth/src/policy/rbac-abac-engine.ts'],
    verificationCriteria: '7 unit tests đánh giá ma trận phân quyền pass 100%.',
    tag: 'Security',
  },
  {
    id: 'task-1-3',
    stageNumber: 1,
    title: 'Đặc tả Giao thức Xoay vòng Token Kép (Token Rotation DAG)',
    description: 'Mô hình hóa DAG chuyển trạng thái token, phân tách Cookie Lax/Strict, cơ chế Grace Period 30s.',
    status: 'COMPLETED',
    deliverables: ['services/auth/src/session/token-rotation-service.ts', 'packages/contracts/src/auth.ts'],
    verificationCriteria: 'Unit tests mô phỏng Grace Period và phát hiện Token Reuse Attack thành công.',
    tag: 'Security',
  },
  {
    id: 'task-1-4',
    stageNumber: 1,
    title: 'Client Auth Interceptor với Mutex Lock',
    description: 'Xây dựng interceptor cho client Next.js ngăn race conditions khi token hết hạn trên nhiều request song song.',
    status: 'COMPLETED',
    deliverables: ['packages/auth-client/src/interceptor.ts'],
    verificationCriteria: 'Kiểm thử 2 request đồng thời chỉ kích hoạt duy nhất 1 lần refresh.',
    tag: 'Frontend',
  },

  // GIAI ĐOẠN 2
  {
    id: 'task-2-1',
    stageNumber: 2,
    title: 'Lược đồ Cơ sở Dữ liệu PostgreSQL 16 Mở Rộng',
    description: 'Thiết kế bảng không gian (spaces), chủ đề (threads), bộ đếm nguyên tử (thread_counters), bình luận phân cấp ltree.',
    status: 'COMPLETED',
    deliverables: ['deploy/migrations/000002_create_community_schema.up.sql'],
    verificationCriteria: 'Bật extensions ltree, pgcrypto, pg_trgm, uuid-ossp thành công.',
    tag: 'Database',
  },
  {
    id: 'task-2-2',
    stageNumber: 2,
    title: 'Hệ thống Design Tokens Đa Chế Độ & Bố Cục 3 Cột',
    description: 'Xây dựng Design Tokens (Dark/Light mode, Typography scale, Spacing, Elevation) và Tailwind Preset.',
    status: 'COMPLETED',
    deliverables: ['packages/ui-tokens/src/tokens.ts', 'docs/stage-2/UI_UX_DESIGN_SPECIFICATION.md'],
    verificationCriteria: 'Đầy đủ cấu hình breakpoint, bảng màu semantic và layout constants.',
    tag: 'Frontend',
  },
  {
    id: 'task-2-3',
    stageNumber: 2,
    title: 'Hợp đồng Khế ước Giao tiếp OpenAPI 3.1 & SSE',
    description: 'Đặc tả OpenAPI YAML cho toàn bộ endpoint Auth, Spaces, Threads, Comments và Realtime SSE.',
    status: 'COMPLETED',
    deliverables: ['packages/contracts/openapi.yaml', 'packages/contracts/src/index.ts'],
    verificationCriteria: 'Schema Zod và kiểu TypeScript khớp 100% với khế ước OpenAPI.',
    tag: 'Architecture',
  },
  {
    id: 'task-2-4',
    stageNumber: 2,
    title: 'Động cơ Bình Chọn Redis Lua Script Nguyên Tử O(1)',
    description: 'Kịch bản Lua script thực hiện đồng bộ upvote/downvote/unvote trên Redis cache và bảng đếm.',
    status: 'COMPLETED',
    deliverables: ['deploy/redis/execute_vote.lua', 'services/community/tests/lua-vote.test.ts'],
    verificationCriteria: '4 unit tests kiểm thử trạng thái bình chọn pass 100%.',
    tag: 'Backend',
  },
  {
    id: 'task-2-5',
    stageNumber: 2,
    title: 'Thuật toán Gravity Decay Xếp Hạng Bài Viết',
    description: 'Công thức suy giảm trọng lực theo thời gian Score = (U - D) / (T + 2)^1.8.',
    status: 'COMPLETED',
    deliverables: ['services/community/src/ranking/gravity-decay.ts'],
    verificationCriteria: '2 unit tests kiểm thử độ phân rã điểm số pass 100%.',
    tag: 'Algorithm',
  },
  {
    id: 'task-2-6',
    stageNumber: 2,
    title: 'Thuật toán Trải Phẳng Cây Bình Luận Phân Cấp O(N)',
    description: 'Hàm flattenCommentTree chuyển đổi cây phân cấp vô hạn thành mảng phẳng cho danh sách ảo hóa.',
    status: 'COMPLETED',
    deliverables: ['packages/tree-virtualizer/src/flatten-tree.ts'],
    verificationCriteria: '3 unit tests kiểm tra độ sâu, thứ tự DFS và thụt lề pass 100%.',
    tag: 'Algorithm',
  },

  // GIAI ĐOẠN 3
  {
    id: 'task-3-1',
    stageNumber: 3,
    title: 'Khởi tạo Cấu trúc Monorepo & Khung Ứng dụng',
    description: 'Thiết lập apps/web (Next.js 15 standalone), apps/api (Node HTTP Gateway) và cấu hình pnpm workspace.',
    status: 'COMPLETED',
    deliverables: ['apps/web/package.json', 'apps/api/package.json', 'pnpm-workspace.yaml'],
    verificationCriteria: 'pnpm recursive build & typecheck hoàn tất không có lỗi.',
    tag: 'DevOps',
  },
  {
    id: 'task-3-2',
    stageNumber: 3,
    title: 'Môi Trường Docker Compose Đa Dịch Vụ Cục Bộ',
    description: 'Điều phối cụm 4 container (PostgreSQL 16, Redis 7, Core API, Web Client) chỉ với 1 câu lệnh.',
    status: 'COMPLETED',
    deliverables: ['deploy/docker/docker-compose.dev.yml', 'deploy/docker/init-db.sql'],
    verificationCriteria: 'Khởi động docker compose up thành công, nạp đầy đủ schemas.',
    tag: 'DevOps',
  },
  {
    id: 'task-3-3',
    stageNumber: 3,
    title: 'Multi-stage Dockerfile Tối Ưu Hóa Kích Thước',
    description: 'Đóng gói Dockerfile.api.prod (<100MB) và Dockerfile.web.prod (<150MB Next.js standalone).',
    status: 'COMPLETED',
    deliverables: ['deploy/docker/Dockerfile.api.prod', 'deploy/docker/Dockerfile.web.prod'],
    verificationCriteria: 'Chạy dưới non-root user, tích hợp healthcheck probe /healthz.',
    tag: 'DevOps',
  },
  {
    id: 'task-3-4',
    stageNumber: 3,
    title: 'Tự Động Hóa CI/CD 4 Cổng GitHub Actions',
    description: 'Thiết lập pipeline tự động hóa: Cổng 1 (Lint) -> Cổng 2 (Typecheck) -> Cổng 3 (Tests) -> Cổng 4 (Docker Syntax).',
    status: 'COMPLETED',
    deliverables: ['.github/workflows/ci.yml'],
    verificationCriteria: 'Kích hoạt thành công trên GitHub Actions cloud runner.',
    tag: 'DevOps',
  },
  {
    id: 'task-3-5',
    stageNumber: 3,
    title: 'Bản Thiết Kế Đám Mây Render Blueprint (IaC) & Chống Ngủ Đông',
    description: 'Khai báo render.yaml triển khai tự động, kèm kịch bản keep-alive.sh ping mỗi 10 phút.',
    status: 'COMPLETED',
    deliverables: ['deploy/render/render.yaml', 'deploy/scripts/keep-alive.sh'],
    verificationCriteria: 'Cấu hình blueprint hợp lệ, tự động ánh xạ PORT và environment variables.',
    tag: 'DevOps',
  },

  // GIAI ĐOẠN 4
  {
    id: 'task-4-1',
    stageNumber: 4,
    title: 'Hiện thực hóa Phân hệ Auth 4.1 (Core Auth Subsystem)',
    description: 'Hoàn thiện PostgresUserRepository, RedisSessionStore (Grace Period 30s, Token Reuse), REST Router (7 endpoints) và Web Client.',
    status: 'COMPLETED',
    deliverables: [
      'services/auth/src/repository/postgres-user-repository.ts',
      'services/auth/src/session/redis-session-store.ts',
      'apps/api/src/routes/auth-router.ts',
      'apps/api/tests/auth-endpoints.test.ts',
      'apps/web/src/lib/auth-client.ts',
    ],
    verificationCriteria: '8/8 HTTP integration tests pass 100%, tổng 45 unit tests monorepo pass.',
    tag: 'Security',
  },
  {
    id: 'task-4-2',
    stageNumber: 4,
    title: 'Giao diện Web Bọc Tài Liệu (Documentation Portal)',
    description: 'Xây dựng cổng tra cứu tài liệu chuyên sâu (/docs), tích hợp cheat sheets, tìm kiếm Ctrl+K và checklist 7 giai đoạn.',
    status: 'IN_PROGRESS',
    deliverables: ['apps/web/src/app/docs/', 'apps/web/src/lib/docs-data/'],
    verificationCriteria: 'Trang tài liệu hoạt động mượt mà, hỗ trợ tìm kiếm và tra cứu ghi chú kỹ thuật.',
    tag: 'Frontend',
  },
  {
    id: 'task-4-3',
    stageNumber: 4,
    title: 'Phân hệ Không gian Thảo luận (Spaces Subsystem)',
    description: 'Tạo, quản lý không gian chủ đề, phân quyền SpaceMod, thiết lập quy chuẩn nội dung.',
    status: 'PLANNED',
    deliverables: ['services/community/src/spaces/'],
    verificationCriteria: 'CRUD Spaces với phân quyền RBAC/ABAC.',
    tag: 'Backend',
  },
  {
    id: 'task-4-4',
    stageNumber: 4,
    title: 'Phân hệ Bài viết Thảo luận (Threads Subsystem)',
    description: 'Đăng tải bài viết, gán thẻ tag, tính điểm nổi bật Gravity Decay theo thời gian thực.',
    status: 'PLANNED',
    deliverables: ['services/community/src/threads/'],
    verificationCriteria: 'Hỗ trợ markdown content, bộ đếm thread_counters nguyên tử.',
    tag: 'Backend',
  },
  {
    id: 'task-4-5',
    stageNumber: 4,
    title: 'Phân hệ Bình luận Phân cấp ltree (Comments Subsystem)',
    description: 'Trả lời đa tầng ltree Base36, trải phẳng cây bình luận ảo hóa O(N).',
    status: 'PLANNED',
    deliverables: ['services/community/src/comments/'],
    verificationCriteria: 'Độ sâu ltree không giới hạn, truy vấn nhánh con <@ tối ưu.',
    tag: 'Backend',
  },
  {
    id: 'task-4-6',
    stageNumber: 4,
    title: 'Phân hệ Biên tập Đa phương tiện Zero-Hop (CMS Pipeline)',
    description: 'Tải ảnh trực tiếp lên Cloudflare R2 qua presigned URL, tạo Blurhash client-side, xác nhận hai pha (2PC).',
    status: 'PLANNED',
    deliverables: ['services/community/src/media/'],
    verificationCriteria: 'Không đi qua backend server (Zero-hop), resize WebP client-side.',
    tag: 'Backend',
  },
  {
    id: 'task-4-7',
    stageNumber: 4,
    title: 'Phân hệ Thông báo & Cập nhật Thời gian thực (SSE Realtime)',
    description: 'Server-Sent Events đẩy cập nhật điểm vote, bình luận mới và thông báo danh tiếng.',
    status: 'PLANNED',
    deliverables: ['apps/api/src/routes/sse-router.ts'],
    verificationCriteria: 'Kết nối SSE giữ vững, tự động reconnect.',
    tag: 'Realtime',
  },
];
